# Generated by Django 4.1.3 on 2022-11-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('listened', models.CharField(choices=[('F', 'Listened to a few songs'), ('A', 'Listened to the first half'), ('B', 'Listened to the second half'), ('W', 'Listened to the whole record')], default='F', max_length=1)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.record')),
            ],
        ),
    ]
