# Generated by Django 4.1.3 on 2022-11-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_spun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spun',
            name='date',
            field=models.DateField(verbose_name='Last Spun'),
        ),
        migrations.AlterField(
            model_name='spun',
            name='listened',
            field=models.CharField(choices=[('F', 'A few songs'), ('A', 'The first half'), ('B', 'The second half'), ('W', 'The whole record')], default='F', max_length=1),
        ),
    ]
