# Generated by Django 4.1.3 on 2022-11-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_spun_date_alter_spun_listened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spun',
            options={'ordering': ['-date']},
        ),
    ]
