# Generated by Django 4.1.3 on 2022-11-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_record_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='fav_lyrics',
        ),
    ]
